USE [master]
GO

/****** Object:  Database [TutorialDB05]    Script Date: 13/11/2021 1:20:59 p. m. ******/
CREATE DATABASE [TutorialDB05]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TutorialDB05', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TutorialDB05.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TutorialDB05_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TutorialDB05_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TutorialDB05].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TutorialDB05] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TutorialDB05] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TutorialDB05] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TutorialDB05] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TutorialDB05] SET ARITHABORT OFF 
GO

ALTER DATABASE [TutorialDB05] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TutorialDB05] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TutorialDB05] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TutorialDB05] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TutorialDB05] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TutorialDB05] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TutorialDB05] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TutorialDB05] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TutorialDB05] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TutorialDB05] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TutorialDB05] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TutorialDB05] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TutorialDB05] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TutorialDB05] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TutorialDB05] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TutorialDB05] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TutorialDB05] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TutorialDB05] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TutorialDB05] SET  MULTI_USER 
GO

ALTER DATABASE [TutorialDB05] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TutorialDB05] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TutorialDB05] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TutorialDB05] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TutorialDB05] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TutorialDB05] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TutorialDB05] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TutorialDB05] SET  READ_WRITE 
GO


